clothes-store:
  services:
    store:
      uri: http://localhost:8081
      registration-id: keycloak
spring:
  boot:
    admin:
      client:
        url: http://localhost:8085
        instance:
          name: manager-app
          service-host-type: ip
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/realms/clothes-store
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: uXlXgajk976Eoiz1NfPiSnQqfoEY8fow
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: manager-app-metrics-client
            client-secret: Fjw89JUz4Gky9t2Su9MdIvQPvvtz5BWz
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8083/realms/clothes-store
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'