clothes-store:
  services:
    store:
      uri: http://localhost:8081
      registration-id: keycloak
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/realms/clothes-store
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: uXlXgajk976Eoiz1NfPiSnQqfoEY8fow
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt