server:
  port: 8085
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/feedback
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/clothes-store
